---
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: false
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit.git
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
...
